logging:
  config: classpath:logback-spring.xml
  level:
    root: info
    org.springframework: info
    com.smartcode: debug

server:
  port: 8089

spring:
  profiles:
    active: dev
  aop:
    auto: true
    proxy-target-class: true
  application:
    name: csw
  datasource:
    url: jdbc:mysql://10.0.4.8:3306/books?useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: csdiao210!
    hikari:
      connection-timeout: 10000
      validation-timeout: 3000
      idle-timeout: 60000
      login-timeout: 5
      max-lifetime: 60000
      maximum-pool-size: 10
      minimum-idle: 5
      read-only: false
  config:
    activate:
      on-profile:
  cache:
    redis:
      cache-null-values: false
  redis:
    lettuce:
      pool:
        max-active: 8 # 连接池最大连接数
        max-idle: 8 # 连接池最大空闲连接数
        min-idle: 0 # 连接池最小空闲连接数
        max-wait: -1ms # 连接池最大阻塞等待时间，负值表示没有限制
    host: 127.0.0.1
    port: 6379
    password: csdiao210


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

cos:
  secretId: AKIDEI7f0A5mERQAfute9PQDk24pKabeV5OQ
  secretKey: nRq0tXv3vXswkIYXFgqiJdgT6WfW7RVI
  region: ap-shanghai
  bucket: booklib-1309974988
  baseUrl: https://booklib-1309974988.cos.ap-shanghai.myqcloud.com/